### ISSUE TITLE
Workloads → Pods: In Pods table "Node" and "Workloads" did not populate (shows “-”) 

### ISSUE THREAD

**Issue by DannyDTenacious** [defenseunicorns/uds-runtime#170]
Workloads → Pods: In Pods table "Node" and "Workloads" did not populate (shows “-”) 

### Visual Proof (screenshots, videos, text, etc)
<img width="772" alt="Screenshot 2024-08-07 at 2 48 10 PM" src="https://github.com/user-attachments/assets/afc4ab1b-97fc-408b-90d7-88c0d274f220">

**Comment by TristanHoladay** [comment]
@DannyDTenacious can you clarify what "Workloads" are not loading? i didn't see that as a column. I checked `Restarts` and that is showing the correct number when pods have restarts (most don't though). The node is not populating because we're now getting sparse data (no `.spec`) so there's no node name to grab. if i change the call to dense the node name shows, but we wanted to avoid getting the dense data for pods because of the load. i think @jeff-mccoy 's json path PR will allow us to get that field without getting the rest of the dense data, but not sure when that will be ready. should we remove the node column for now?

![Screenshot from 2024-08-07 19-58-02](https://github.com/user-attachments/assets/1745bf3c-c454-43fc-9347-2107a54bc8d0)

**Comment by DannyDTenacious** [comment]
Sorry, that was a mis-type. The only columns that were in questions were "Restart" and "Node" columns. I don't think hiding these columns is needed for now - it shouldn't negatively impact user feedback at this stage. I do think it would be helpful to distinguish the values would be helpful in the short term. Something like "If value = "0" then show "0". If value is not being pulled but will be in the future then show "TBD" or something. Maybe this merits a discussion for the team?

**Comment by TristanHoladay** [comment]
after talking with the others, we ended up putting the nodename as a conditional field in the sparse data so it will show for pods.
