### ISSUE TITLE
Runtime Deployed with UDS Core

### ISSUE THREAD

**Issue by adam-defenseunicorns** [defenseunicorns/uds-runtime#346]
### Is your feature request related to a problem? Please describe

To make the most seamless user experience possible we would like UDS Runtime to become a package with UDS core that deploys like the rest of the tools and services. 

### Describe the solution you'd like

- **Given** a platform Engineer
- **When** UDS Core is deployed 
- **Then** UDS Runtime is also deployed as a package in UDS Core

### Describe alternatives you've considered

- Making Runtime a completely optional package that would have to be deployed separately using UDS CLI

### Additional context

More exploration will likely be necessary to sort out how this change ties into UDS Core Functional layers but the assumption is that most users will want runtime deployed with the rest of the tools and services for UDS.

**Comment by adam-defenseunicorns** [comment]
@mjnagel would like to get your thoughts here as it pertains to functional layers.

**Comment by mjnagel** [comment]
High level what I see that would be needed:
- Move/duplicate the [zarf.yaml](https://github.com/defenseunicorns/uds-runtime/blob/main/zarf.yaml) for runtime into core
- Remote reference the chart for runtime so that dev work on runtime can continue in this repo
- import the runtime component into the standard zarf package for core
- when functional layers is implemented, add runtime as a func layer as well
